# Site settings
title: LinguÁgil 2015
email: linguagil@linguagil.com.br
description: "Evento LinguÁgil, o maior evento sobre linguagens de programação e metodologias ágeis de Salvador/BA."
baseurl: ""
url: "http://2015.linguagil.com.br"
twitter_username: https://twitter.com/linguagil
facebook_username: https://www.facebook.com/linguagil
github_username:  linguagil
local_links:
  -
    title: "Início"
    url: "#top"
  -
    title: "Sobre"
    url: "#about"
  -
    title: "Saiba mais"
    url: "#services"
  -
    title: "Inscrição"
    url: "#registration"
  -
    title: "Localização"
    url: "#location"
# Build settings
markdown: kramdown
permalink: pretty
